/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pkhope_screenrecorder_NativeGifEncorder */

#ifndef _Included_com_pkhope_screenrecorder_NativeGifEncorder
#define _Included_com_pkhope_screenrecorder_NativeGifEncorder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pkhope_screenrecorder_NativeGifEncorder
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pkhope_screenrecorder_Recorder_NativeGifEncorder_test
  (JNIEnv *, jclass);

/*
 * Class:     com_pkhope_screenrecorder_NativeGifEncorder
 * Method:    open
 * Signature: (Ljava/lang/String;III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pkhope_screenrecorder_Recorder_NativeGifEncorder_open
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     com_pkhope_screenrecorder_NativeGifEncorder
 * Method:    addFrame
 * Signature: (Landroid/graphics/Bitmap;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pkhope_screenrecorder_Recorder_NativeGifEncorder_addFrame
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_pkhope_screenrecorder_NativeGifEncorder
 * Method:    save
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_pkhope_screenrecorder_Recorder_NativeGifEncorder_save
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
